# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/algorithmic-gamer',
                'doc_host': 'https://TannerLaBorde.github.io',
                'git_url': 'https://github.com/TannerLaBorde/algorithmic-gamer',
                'lib_path': 'algorithmic_gamer'},
  'syms': {'algorithmic_gamer.core': {'algorithmic_gamer.core.foo': ('core.html#foo', 'algorithmic_gamer/core.py')}}}
