# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/algorithmic-gamer',
                'doc_host': 'https://TannerLaBorde.github.io',
                'git_url': 'https://github.com/TannerLaBorde/algorithmic-gamer',
                'lib_path': 'algorithmic_gamer'},
  'syms': { 'algorithmic_gamer.fuzzer': { 'algorithmic_gamer.fuzzer.fuzzy_app': ( 'utility/application_fuzzer.html#fuzzy_app',
                                                                                  'algorithmic_gamer/fuzzer.py'),
                                          'algorithmic_gamer.fuzzer.get_window_names': ( 'utility/application_fuzzer.html#get_window_names',
                                                                                         'algorithmic_gamer/fuzzer.py'),
                                          'algorithmic_gamer.fuzzer.resolve_window_name': ( 'utility/application_fuzzer.html#resolve_window_name',
                                                                                            'algorithmic_gamer/fuzzer.py')},
            'algorithmic_gamer.types': { 'algorithmic_gamer.types.Region': ('types.html#region', 'algorithmic_gamer/types.py'),
                                         'algorithmic_gamer.types.Window': ('types.html#window', 'algorithmic_gamer/types.py')},
            'algorithmic_gamer.vision': { 'algorithmic_gamer.vision.f_get_region': ( 'vision.html#f_get_region',
                                                                                     'algorithmic_gamer/vision.py'),
                                          'algorithmic_gamer.vision.f_view': ('vision.html#f_view', 'algorithmic_gamer/vision.py')}}}
