# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto 0
__all__ = ['Region', 'Window']

# %% ../nbs/00_types.ipynb 1
from dataclasses import dataclass

# %% ../nbs/00_types.ipynb 4
@dataclass
class Region:
    left: int
    top: int
    right: int
    bottom: int

# %% ../nbs/00_types.ipynb 7
@dataclass
class Window:
    app_name: str
    sub_region: Region = None
