name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: quarto-dev/quarto-actions/setup@v2
    - name: Test quarto command
      run: quarto --version
    - uses: fastai/workflows/quarto-ghp@master

