name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Download MSI
      run: curl -L -o quarto-1.2.280-win.msi https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.280/quarto-1.2.280-win.msi
    - name: Install MSI
      run: pwsh -command "& 'C:\Windows\System32\msiexec.exe' /i quarto-1.2.280-win.msi /qn"
    - name: Update PATH environment variable
      run: |
        $env:PATH = "$env:ProgramFiles\Quarto\bin;$env:PATH"
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::Machine)
    - name: Reboot runner if necessary
      if: steps.install.outputs.exit_code == 3010
      run: Restart-Computer -Force
    - uses: fastai/workflows/quarto-ghp@master

